name: MCTrapsDisplayer
version: 1.5.0
author: KajmaczeK
main: eu.mctraps.MCTrapsDisplayer.MCTrapsDisplayer
website: https://mctraps.eu
#depend: [ActionBarAPI]
commands:
  displayer:
    description: "Główna komenda pluginu"
    usage: /<command>
    permission: tools.displayer.admin
  bar:
    description: "Wyswietl wiadomosc na ActionBarze"
    usage: /<command>
    aliases: [actionbar]
    permission: tools.displayer.bar
  titled:
    description: "Wyswietl wiadomosc jako Title"
    usage: /<command>
    permission: tools.displayer.title
#  voucher:
#    description: "Komenda do obsługi voucherów"
#    aliases: [vouchers]
#    usage: /<command> <list|info|add|remove|edit>
#    permission: tools.smsshop.voucher
permissions:
  tools.displayer.*:
    description: "Wszystkie uprawnienia pluginu"
    default: op
    children:
#      - tools.smsshop.admin
#      - tools.smsshop.voucher
      - tools.smsshop.bar
#  tools.smsshop.admin:
#    description: "Pozwala na użycie głównej komendy"
#    default: op
#  tools.smsshop.voucher:
#    description: "Pozwala na obsługę voucherów"
#    default: op
  tools.displayer.bar:
    description: "Pozwala na wysyłanie wiadomości na ActionBarze"
    default: op
  tools.displayer.titled:
    description: "Pozwala na wysyłanie wiadomości jako Title"
    default: op