language: java
jdk:
- oraclejdk8
sudo: required
script: mvn clean verify
before_install:
- sudo apt-get install -y rsync
- sudo apt-get install -y expect
after_success:
- chmod 770 .travis/notification.sh
- .travis/notification.sh "MCTrapsDisplayer build ended"
branchers:
  only:
  - master
  except:
  - "/^untagged-(.*)$/"
deploy:
  provider: releases
  api_key:
    secure:
      secure: zXAZZp3ghjTcXTi3l+NKiE21HInBmAPCP1SzDqrH1Ct7O2NsLTahd7i6Jr10U/dAHsRwdL+Z7SwT81yeFbqm+srILeHGOITu8mY3HQgADqLtHOn9QzCfUDK669BMSUruLhNgq71iSotlwU2TJA8knxj22v8bmNh4I+SHu0vwMI7boYI9vr8RU6Rz4d+SId1cRp422mpbAu08vblkiHae8D3mlayC/Vjw/5DspGU/9BrEctPpCYf/V72KAn8IZSF54jjewESCtk8booixlQKnKo5cD4RTFhXlRToG9b/J/0xCyXWbmo/8S+QurZmA/8u+bMK5N/Sy1HTS27VpZadRM2cWckgVQ1W2Y/ELRLe875Q/gLz1Bd9OSByRXIRxoIdBrfFmk9w9Ve3D/dyM1gdbcsxqcBpTDC+rE7HxspI/WMAIcG4KgISzc2EalVfA1KwyMcLBxR+YC1bReuvjCKg60hl5fNfq+5WsMFP+QOTIfkZ5KMBXlGl/RsJC5YN+thfbnxu2CkknmVu0F488INDuz/U8aYNpgO4rx4D+sG/wCbEdFKBvkXTe2qwno5hY7R33ecqp3Lynr1RwKr6lqGHU+itIVhO63UUypr3vTP1PJM2mr6Pcm8WEq2m0yFgeCSHPCiCFk++4W1OWKGmGd7wDYcmiTjVD62Z67SOv9xSijYA=
  file: "/home/travis/build/MrKajmaK/MCTrapsShop/target/MCTrapsDisplayer.jar"
  skip_cleanup: true
  on:
    repo: MrKajmaK/MCTrapsDisplayer
    branch: master
    tags: true
